modules/protocol/hybrid.cpp
- Increase MaxModes to 6
- SendLogout(): send "+d *" instead of "+d 0"
- Update copyright year
- Removed user mode +z from supported modes
=> Misc changes to the ircd-hybrid protocol module:

modules/commands/cs_set.cpp
=> Revert "Added kickcheck override for users with protected privs"

language/anope.fr_FR.po
Fixed [Bug #0001648](http://bugs.anope.org/view.php?id=1648)
=> Placeholder left in French Translation

language/anope.el_GR.po
Updated and fixed all the non-fuzzy languages items, previously all of them was incorrect.
Added new credits.
=> Updated and fixed the Greek language.

modules/protocol/charybdis.cpp
Adds support for MECHLIST in protocol/charybdis
=> proto/charybdis: Add support for MECHLIST

include/protocol.h, modules/m_sasl.cpp, modules/protocol/charybdis.cpp, modules/protocol/inspircd12.cpp, modules/protocol/inspircd20.cpp, modules/protocol/unreal.cpp, modules/protocol/unreal4.cpp
Only charybdis seems to support that for the moment.
=> Send vident/vhost in SVSLOGIN with SASL

modules/protocol/ratbox.cpp
Normal join: `:10UAAAAD8 JOIN 1423850819 #test +`
/join 0: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`:10UAAAAD8 JOIN 0`
=> Handle /join 0 for ratbox & charybdis

modules/protocol/charybdis.cpp
Properly support RESV and UNRESV in Charybdis, and improve RESV setting for pseudoclients when bursting.
=> charybdis.cpp: Properly support RESVs

language/anope.fr_FR.po
Update the French translation.
Thanks to @Natolumin  for reporting some typos.
=> Update French language file.

language/anope.fr_FR.po
- translate "nick" to "pseudo"
- remove "XOP" arg from set secureops
=> Update French language file

modules/commands/ns_group.cpp
Reported in #anope by @KoraggKnightWolf
=> Log NickServ ungroup

modules/webcpanel/templates/default/nickserv/access.html
id and name values was wrong in nickserv/access template file
=> Fixed NickServ set access from webcpanel

modules/commands/cs_enforce.cpp
Typo was pointed out by one of my users.  
Not sure if I should touch the language files or leave that for a possibly larger updating.
=> Fix typo in CS enforce help reply.

data/example.conf
It seems that the massive line of text above these is not enough to make it clear so add a comment on each of them.
=> Make it more clear where the uplink config goes.

data/modules.example.conf
Fixed stupid simple typo, changed "bot not both" to "but not both"
=> Fixed stupid simple typos.

data/example.conf, data/stats.standalone.example.conf, docs/README, include/modes.h, modules/protocol/inspircd3.cpp, src/modes.cpp
This should work fine but it'll require a bit more testing.
Note: this depends on #241.
=> Add support for the InspIRCd 1205 protocol.

include/account.h, include/anope.h, modules/protocol/inspircd3.cpp, src/init.cpp, src/nickcore.cpp, src/siphash.cpp
Problems left to solve with this:
=> Implement support for immutable account identifiers.

modules/commands/ns_resetpass.cpp
Reply need to be always sent, this enable this command to be executed also using xmlrpc
=> Reply need to be always sent

language/anope.it_IT.po
Hi,
I've fixed a typo in the Italian translation.
=> [Translation] Fixes typo in Italian translation

modules/protocol/hybrid.cpp
* Add METADATA command handler which currently only allows to modify a client's certificate fingerprint
* Minor reformatting and style inconsistency fixes
=> Update ircd-hybrid protocol module

language/update.sh
If it’s too much change for one commit, I could try to split it up. I just thought I’d try it like this first (;
=> fix: make language/update.sh safer, faster, cleaner

data/modules.example.conf
=> Fix missing end of comment

data/CMakeLists.txt, docs/INSTALL, docs/INSTALL.fr
Update the cron file name in the places where it still pointed to example.chk
Avoid confusing users
I have tested this pull request on:
**Operating system name and version:** Ubuntu 24.04.1 LTS
**Compiler name and version:** gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
=> Update the cron file name

language/anope.pt_PT.po
Here are some more translated entries.
I will continue to work on this as best I can.
=> Continuation of the translation

language/anope.fr_FR.po
=> Fix French translation of "last used"
