anope/anope

modules/commands/cs_entrymsg.cpp

Makes the ability to control ENTRYMSG's assignable instead of restricted to only the channel founder.

cs_entrymsg to use SET permission, not isFounder

---

modules/m_xmlrpc.cpp

XML-RPC responses use the methodResponse tag, not methodCall.

Correct wrong XML response tag

---

modules/protocol/hybrid.cpp

- best supported version is 8.2.x
- fixed UID message handler to cope with account names being '*'
- minium required TS version is TS6 now

- Misc updates to the hybrid protocol modules:

---

modules/commands/cs_set.cpp

I think should be useful having this override for users with protected privs (Can not be kicked from channels by Services)

Added kickcheck override for users with protected privs

---

modules/m_xmlrpc.cpp

Following http://xmlrpc.scripting.com/spec.html

XML-RPC responses also don't have a methodName tag

---

modules/commands/cs_access.cpp

Commit 96583892c6a0bc48029348ddcf86b1afc5a9915d introduced the `chanserv/access/list` privilege for the `/cs access list` command. This commit reuses it for `/cs levels list` to provide opers with a read-only access to the levels, in addition to the `chanserv/access/modify` privilege which already provides read and write access.

Allow opers with chanserv/access/list to view the levels list

---

modules/database/db_flatfile.cpp

The code only looks for 'nobackupok' and 'nobackupokay' was ignored.

Fix db_flatfile to read the "nobackokay" setting

---

modules/protocol/inspircd20.cpp

It isn't as serious as it sounds as you need access to change channel modes via ChanServ to perform the escalation which by default requires channel operator privileges. However, if you have those privileges and the server has status modes higher than op (i.e. +Yyao) enabled then you can set +w masks to give people those any of those status modes.
Workaround for this bug is to unload m_autoop on InspIRCd. You don't need it anyway if you're using Anope.

Fix a low risk privilege escalation exploit on InspIRCd with m_autoop.

---

include/protocol.h
modules/m_sasl.cpp
modules/protocol/inspircd20.cpp

The protocol side is implemented for InspIRCd but not for other daemons (i.e. @charybdis-ircd) as i'm not familiar enough with their protocols to implement it.

Implement support for SASL 3.2 mechanism lists.

---

modules/protocol/charybdis.cpp

Before : 
```
USERS: nick!~ident@* (my.reverse-dns.tld) (gecos) [xx.xxx.xxx.xx] connected to the network (irc.mynetwork.tld)
```
After : 
```
USERS: nick!~ident@my.reverse-dns.tld (gecos) [xx.xxx.xxx.xx] connected to the network (irc.mynetwork.tld)
```

Fix host on charybdis if there is no vhost

---

extras

This is fairly harmless but it could cause issues for some people who are building from old git clones.

Remove references to cmake-bin which was removed ages ago.

---

CMakeLists.txt
include/anope.h
src/misc.cpp

To aid build reproducibility, don't include the build date/time if
-DREPRODUCIBLE_BUILD is defined.
Based on the patch provided by Alexis Bienvenüe in the Debian report.
Bug-Debian: https://bugs.debian.org/820152
Patch-Name: reproducible_datetime.diff

Optionally strip variable build date from compiled program

---

Config

Some spartan systems don't include which which resulted in misleading error messages.

Use "cmake --version" instead of "which cmake" to detect CMake.

---

data/example.conf

It seems to me that these commands have been removed and replaced by the chanserv/administration privilege. So I think that they should no longer mentioned in the config. Please tell me what you all think of this.

Remove unused commands from oper config.

---

src/tools/anopesmtp.cpp

Was seeing Anope's emails (through anopesmtp) getting flagged as spam due to missing the required Date header line:
`X-Amavis-Alert  BAD HEADER SECTION, Missing required header field: "Date"`
Adding the Date header line has cleared up the spam flagging.

Added a Date field to the Header

---

modules/protocol/charybdis.cpp
modules/protocol/ratbox.cpp

Also, enable channel support because it wasn't specified already and point charybdis to these methods instead.

ratbox: fix RESVs

---

data/chanserv.example.conf

As seen within this [commit](https://github.com/anope/anope/commit/22658d63bdb1e52a66f4514af45fa55ca5891345)
'expiretimeout' is no longer set within cs_seen and I can't see it used elsewhere to be needed in the config.

Remove 'expiretimeout' from chanserv.example.conf

---

Config

Some people don't read more than the last line.

Don't give misleading instructions when running CMake fails.

---

modules/protocol/inspircd12.cpp
modules/protocol/inspircd20.cpp

This is necessary, for example, with InspIRCd's m_sasl config option `target="services.mynet"`. The ENCAP message contains the target (server name) instead of the ServerID.

protocol/inspircd: Match servername as well on ENCAP

---

include/sockets.h
modules/m_dns.cpp
modules/m_dnsbl.cpp
src/sockets.cpp

Moved m_dns's reverse ip method to sockaddrs::reverse().
(Since m_dnsbl also relies on it, I thought it would be easier to move it to there where it belongs in order to save duplicate code on something generic)
Updated m_dnsbl to support ipv6.

IPv6 support for m_dnsbl and sockaddrs::reverse()

---

modules/m_xmlrpc_main.cpp

Some calls require a user object to work properly (NS/UPDATE, NS/GROUP, etc). This PR allows m_xmlrpc_main to lookup user objects by nickname and impersonate that user if they are online, allowing these calls to work.

Allow calls to XMLRPC to impersonate supplied user, if online

---

data/modules.example.conf

I noticed the SASL module is not loaded by default.
May I suggest changing data/modules.example.conf, from:
#module { name = "m_sasl" }
To:
module { name = "m_sasl" }
So more users will benefit from SASL by default?
Together with the saslmechlist (see other report) I'm seriously considering at UnrealIRCd, if no set::sasl-server is set, to automatically set the sasl-server to services-server if the saslmechlist is received from said services-server, since it's a reliable way to tell that SASL is available.
Current SASL support is quite dramatic, see http://ircstats.org/server-features/cap
I want to bump it from the current 9% (and only 3% for UnrealIRCd) to a lot more, but I need your help for this as well.

Load sasl module by default.

---

modules/protocol/unreal4.cpp

We added support for SASL v3.2 in UnrealIRCd which requires services to send the saslmechlist. I took a look at how you do it with other IRCd's and made a patch.

Advertise SASL mechanisms to UnrealIRCd servers.

---

modules/dns.cpp

gcc warning: ?: using integer constants in boolean context, the expression will always evaluate to ‘true’ [-Wint-in-bool-context]

modules/dns: NotifySocket takes a bool parameter, not int address family

---

modules/commands/bs_set.cpp
modules/commands/cs_set.cpp
modules/commands/ns_set.cpp

This code is duplicated from help.cpp to (bs,cs,ns)_set.cpp for listing
the available SET commands. The check for the 'hide' flag was missed
and this incorrectly listed commands that were configured as hidden.
This was reported by DeviL on IRC about a month ago.

Check for 'hide' flag in commands in (bs,cs,ns)_set HELP

---

modules/commands/ns_set.cpp

The current if statement is backwards, hiding the command when it can be set and displaying it when it cannot be set.

Show NickServ SET MESSAGE in help when 'useprivmsg' is enabled

---

data/operserv.example.conf

This only works on UnrealIRCd 3.2 (which has been EOL for over a year now) and regularly confuses users who think that "your IRCd does not support OMODE" is an error they need to fix.

Disable the os_oline module by default.

---

modules/protocol/inspircd20.cpp

The not explicitly checked for (chan,user)modes in their inital `CAPAB` string are added to a list to be properly added as a Mode during the `CAPABILITIES` line. The logic for both `CHANMODES` and `USERMODES` needs the `commasepstream` to allow empty values to correctly match up at times.
For example: `USERMODES=,,s,BHIRSWcdghikorwx` had the first token returned as `s` and second token as `BHIRSWcdghikorwx` but the code ignores the first two tokens.
Allowing empty values matches things up properly no matter the modes available on Insp and fixes OS UMODE not working for "extra" modes. Usermode 's' (snomask) was also unable to be set/unset with OS UMODE previously and can be now (though you still can't set the parameters this way, only set/unset the mode).

Fix for bug 1712

---

modules/commands/cs_seen.cpp

These strings: " but %s mysteriously dematerialized.", ". %s is still online." and ", but %s mysteriously dematerialized." weren't translated by the method Anope::printf().

Fix for translations being ignored in cs_seen.cpp

---

src/tools/anopesmtp.cpp

After sending the "\r\n.\r\n" after the mail payload, smtp_send_email was not waiting for the mail server to complete post-processing and respond with "250", but was sending "QUIT\r\n" immediately and dropping the connection.  Mail server may kill the transaction if it can't send the "250" (socket closed).  The changes proposed completes the mail transaction by reading for the 250 and in smtp_disconnect steps through a proper quit sequence by waiting for the 221 server response.
I discovered this by including the --debug option in services.conf sendmailpath, which invoked logging in smtp_send and that slowed it down enough for the mail server to return the 250 and complete the transaction.

Fix mail sending for reliability.

---

data/modules.example.conf
include/modules/httpd.h
modules/m_httpd.cpp

This mimics the behavior of `extforward_header` to allow multiple IPs in the `extforward_ip` config option. This is especially useful as most reverse proxies will either use multiple IPs (eg. v4 and v6) or a user may have multiple reverse proxies.

Allow multiple IP addresses in extforward_ip separated by spaces

---

modules/protocol/inspircd20.cpp

This is technically part of the 1205 protocol but it is entirely backwards compatible so older versions will not be negatively affected by this.

Send the casemap as part of CAPAB CAPABILITIES on InspIRCd.

---

modules/protocol/inspircd20.cpp

InspIRCd 2.0 sends a timestamp in its S2S AWAY message since
https://github.com/inspircd/inspircd/commit/b1002b7df55f1aec5bfce48ecd07d6d326174c95
Syntax of `AWAY <timestamp> :<away msg>`
Catch this message and remove the timestamp parameter before
sending it to the core AWAY handler.
**Tested** successfully.
**Edit**: Changed to a modification of the `inspircd20` protocol instead of core.

Handle S2S AWAY messages with a timestamp

---

modules/protocol/unreal4.cpp

This updates the unreal4 protocol module to work with both pseudo-id's
and real UID's. Something that will also be necessary once UnrealIRCd
gets rid of pseudo-id's altogether.

Allow post-handshake SASL in UnrealIRCd 4.2.2 and up.

---

modules/protocol/inspircd20.cpp

This will allow their messages to be marked as originating from bots on InspIRCd v3 (ref: https://github.com/inspircd/inspircd/commit/180b8b6ab194fd74cb5c64fc3ec0775eb542451a).

Mark pseudoclients as bots on InspIRCd if the bot mode exists.

---

include/protocol.h
src/process.cpp
src/protocol.cpp

The InspIRCd v3 1205 protocol (for which I will file a pull request soon) requires servers to be able to understand message tags. This pull request adds support for that. I modified the core parser as the tag syntax is backwards compatible and will be supported by other software in the future.
To avoid having to alter a bunch of `IRCDMessage::Run()` functions to support tags I have added an overload which takes tags and just calls the non-tag variant by default. This allows existing protocol modules for non-tag supporting software to continue without any changes.
This also fixes a defect in the message parser where `COMMAND param1 :param2    param2` is interpreted as `COMMAND param1 :param2 param2` due to the mistaken use of `spacesepstream`.

Update the core message parser to allow parsing IRCv3 message tags.

---

modules/commands/ns_group.cpp
modules/pseudoclients/nickserv.cpp

The config option `unconfirmedexpire` is under the module `ns_register` not the base `nickserv` module.
Reported by @KoraggKnightWolf via IRC.
Thanks to @Adam- for catching the second spot (ns_group.cpp).

Fix NickServ INFO and GLIST showing an incorrect unconfirmed expiry.

---

modules/protocol/inspircd3.cpp

This ext item is how SSL status is known for a user on InspIRCd. This worked with InspIRCd 3 using the `inspircd20` protocol because it inherited from `inspircd12`, which declared this item. The relevant code for `Extend` already exists.
Fixes bug 1728.

inspircd3: Add the SSL ExtensibleItem for Users.

---

modules/protocol/inspircd20.cpp
modules/protocol/inspircd3.cpp

InspIRCd 3 now includes the channel TS in any channel metadata. This requires two changes to how it's handled in this function **(note: this section is only ran for a bursting server):**
- increase the type and value parameter indexes by one.
- update the messages sent from this function to include the TS (creation time).
While testing this I also noticed a minor issue with the topiclock state lookup, `GetExt<bool>("TOPICLOCK")` is always returning a NULL pointer (due to being a `SerializableExtensibleItem<bool>` which by design does not create an object). When the bursting server says topiclock is enabled, this will cause services to disable it. Note: upon services connecting to an uplink it will be enabled again shortly after during OnChannelSync() which runs OnChanRegistered() and sets …

inspircd protocols: Update IRCDMessageMetadata for channel metadata.

---

modules/protocol/inspircd3.cpp

* Fix an inverted if statement.
* Fix setting of the reason, it will always be included in the message from what I can find (minimum parameters is 3); just might be the 3rd or the 4th parameter depending on if the target's membership ID is included or not.
This currently causes weird desyncs since the user isn't removed internally. Credit to @Techman for spotting this as rejoining after a kick resulted in not receiving the expected status modes.
I have tested this on my testnet, both with a local and a remote user; works as expected.

Fix the handling of kick messages with InspIRCd v3.

---

modules/protocol/inspircd3.cpp

The "normal" `FTOPIC` message is only 4 parameters and uses the source as the setter. During burst or in reply to `RESYNC` 5 parameters are supplied, with the setter being supplied before the topic.
Reference: https://github.com/inspircd/inspircd/blob/insp3/src/modules/m_spanningtree/ftopic.cpp#L74-L93
Credit to Dimitris for spotting this bug and reporting it in #anope (no idea if they are on GitHub).

Fix the handling of topic messages with InspIRCd v3.

---

modules/commands/ns_resetpass.cpp

The current wording doesn't work with the `used <command>` added in the log function.
Current log message: `COMMAND: test!g3k@g3k.solutions used CONFIRM confirmed RESETPASS to forcefully identify as test`
New log message: `COMMAND: test!g3k@g3k.solutions used CONFIRM to confirm RESETPASS and forcefully identify as test`

Improve wording of the resetpass:confirm log message.

---

modules/pseudoclients/hostserv.cpp

I decided to file this in the spirit of #259. I agree with @genius3000's statement that this should be handled in HostServCore.
This implementation is fairly simple. If a nick being dropped has a vhost, it is removed.
I've tested:
- Dropping a nickname from the user's perspective
- Dropping a nickname from a network admin's perspective
The end result is the vhost is unset, and the user's cloaked or real host is restored, depending on whether the IRCd being used supports host cloaking.

HostServ: Remove vhost when a nick is dropped

---

src/language.cpp

```
__USE_GNU_GETTEXT is exposed by musl because they provide
a GNU gettext-compatible interface. This doesn't mean they
provide all the internals that glibc does.
Check for __GLIBC__ if using internal _nl_msg_cat_cntr.
```
Signed-off-by: Sam James (sam_c) <sam@cmpct.info>

Fix musl build (gettext internals)

---

data/nickserv.example.conf

When set to `yes` this breaks the `killprotect` functionality, because a user is expected to turn into guest after the specified amount of time.
Also new users that register their nicknames will wonder why they can't join a +R channel but they didn't change their nick to Guest*

Update nickserv.example.conf regarding "addaccessonreg" feature

---

modules/protocol/inspircd3.cpp

Enables support for sending CBANs when a channel SQLine is made. Requires InspIRCd 3.8+ with m_cban configured to allow glob masks.
If m_cban is not configured with glob support, Anope will not send a CBAN and will fall back to its current system of enforcement.

inspircd3: Enable support for channel SQLines

---

src/bots.cpp

This can only be triggered by services operators with permission
to delete a BotServ bot. If the bot is assigned to any channels
when being deleted, a crash could occur.
```
The call to UnAssign() erases the channel from the set which
invalidates the iterator in this loop. Handle this in the same
manner as the NickCore dtor.
```

Fix a possible crash when deleting a BotServ bot.

---

data/global.example.conf

The previous default example (which is in use on many Anope networks) refers to Services in 2nd person, then 1st person - in the same sentence.

data/global.example.conf: Correction

---

modules/extra/m_ldap.cpp

Starting with OpenLDAP 2.5 upstream decided to merge the non-threaded libldap_r library into the threaded libldap library. And starting with OpenLDAP 2.6 common Linux distributions such as Fedora do not ship the compatibility symbolic link anymore (which leads to a build failure), thus the linking should prefer libldap rather than libldap_r.
See also:
- https://lists.openldap.org/hyperkitty/list/openldap-announce@openldap.org/thread/BH3VDPG6IYYF5L5U6LZGHHKMJY5HFA3L/
- https://bugzilla.redhat.com/show_bug.cgi?id=2032707

Reflect OpenLDAP 2.5 upstream change from libldap_r to libldap

---

modules/database/db_flatfile.cpp

On a machine that had disk trouble and a couple of unclean shutdowns, I have had to restore the anope database from an older backup, and noticed empty dated files in the backups/ directory. 
This change decreases the likelihood of ending up with a zero-byte (or missing) anope.db by changing the sequence in which the database is written.
Previously, the code would:
1. Move the existing `anope.db` to `anope.db.tmp` (if the server crashes here, you are missing `anope.db` entirely)
2. Write to `anope.db` (if the server crashes here, you might have an empty `anope.db`)
3. Remove `anope.db.tmp` if the write succeeded, or rename `anope.db.tmp` back to `anope.db` if the write failed.
With this PR, the code will:
1. Write to `anope.db.tmp` (if the server crashes here, the old file is still intact) …

anope database: write to temporary file and rename

---

modules/webcpanel/pages/nickserv/confirm.cpp
modules/webcpanel/pages/nickserv/confirm.h
modules/webcpanel/templates/default/nickserv/confirm.html
modules/webcpanel/webcpanel.cpp
modules/webcpanel/webcpanel.h

This PR allows users who register, using the Anope Webcpanel to login and confirm their email address _(registration)_ with the emailed **CONFIRM code**.

Webcpanel: Add ability to CONFIRM accounts via NickServ tab

---

modules/protocol/unreal4.cpp

This sends the `CHGIDENT` and `CHGHOST` message right before the `SVSLOGIN` (SASL succeeded) message.
For SASL users this means you get the correct vident/vhost straight from the start, which is great for auto-join/re-joins/etc.
I see other protocol modules have this too (inspircd as a separate command like us, and charybdis and plexus in a single protocol message).
This feature will work with UnrealIRCd git of today (https://github.com/unrealircd/unrealircd/commit/977c4b433a51b1a5c88bd271f85cfde60968fd2d). The feature will also be in 6.0.7 stable, scheduled for April 2023.
It is no problem to send the protocol message to older UnrealIRCd servers (just a harmless no such nick/channel being sent back to the services server), in which case the usual post-registration CHGHOST/CHGIDENT will …

unreal4: set vhost/vident during SASL

---

src/messages.cpp

Fix incorrect format specifier
Calling a printf-like function with the wrong type of arguments causes unpredictable behavior.
I have tested this pull request on:
**Operating system name and version:** Ubuntu 20.04 
**Compiler name and version:** GCC 9.4.0

messages: fix incorrect format specifier

---

data/modules.example.conf

Cosmetic change to match the multi-line comment style of the rest of the file.

Add missing whitespace in multi-line comment

---

data/modules.example.conf

Minor change to remove overleft of module with `m_` prefix, because at least in my build, it's `xmlrpc_main.so` now.

Remove overleft of module with m_ prefix

---

modules/protocol/unrealircd.cpp

As (sortof) requested in https://github.com/anope/anope/issues/360, this adds message-tags support for the unrealircd protocol module in anope 2.1. Support for this is auto-detected / enabled conditionally when "MTAGS" is present in "PROTOCTL". This is the case in UnrealIRCd 5.0.0 and later.
The change has been tested with current UnrealIRCd 6.1.5-git by using the CS ENTRYMSG functionality where `+draft/channel-context=` correctly shows up on the client-side. And also tested the other way around, with a (modified) UnrealIRCd which did not have "MTAGS", the message tag does not show up there... as expected.

Enable message-tags support for UnrealIRCd

---

modules/protocol/unreal4.cpp

Backport of https://github.com/anope/anope/pull/378 to anope 2.0.x. Original text below (also did retest with 2.0.x git).
This fixes https://github.com/anope/anope/issues/374 in the sense that we no longer use the `SQLINE` command in server to server traffic to UnrealIRCd when setting a SQLINE, we now use the `TKL` command. This way the expiry time that anope wants can be communicated to UnrealIRCd. Commands like `OS SQLINE ADD +1m ...` work properly now and for `OS FORBID` it will obey the 15 seconds that anope uses (or whatever 'inhabit' is set to by the admin).
This has been tested on UnrealIRCd 6.1.5-git. The `TKL` command syntax should be fine for any UnrealIRCd in the past 20 years or so, so we should be good :D.

Fix OS SQLINE expiry with UnrealIRCd

---

data/modules.example.conf
modules/extra/mysql.cpp

This pull-request adds the ability to use unix sockets with the mysql module
Unix sockets have less overhead than tcp
I have tested this pull request on:
**Operating system name and version:** ArchLinux 6.9.7-arch1-1 x86_64
**Compiler name and version:** gcc (GCC) 14.1.1 20240522
mariadb 11.4.2-1, mariadb-libs 11.4.2-1 (libmariadbclient)

Add unix socket support to mysql module

---

include/services.h

Adds `#include <cstring>` to include/services.h as quite a few musl libc systems fail to build without it. It was needed in many places so figured a single add to services.h is best.
To allow musl distros (voidlinux and others) to package without having to patch it
locally and on a small network of 50ish users
I have tested this pull request on:
**Operating system name and version: void linux kernel 6.10
**Compiler name and version: gcc 13.2

fix build on some musl systems
